import GameBoard from "../modules/gameboard.js";
import { Player, ComputerPlayer } from "../modules/player.js";
import Ship from "../modules/ship.js";

describe("Player tests", () => {
	let realPlayer;
	let compPlayer;
	beforeAll(() => {
		realPlayer = new Player("player", 10);
		realPlayer.gameBoard.placeShip(4, "vertical", 3, 0);
		compPlayer = new ComputerPlayer(10);
		compPlayer.gameBoard.placeShip(3, "horizontal", 3, 3);
	});
	test("Player class should exist", () => {
		expect(Player).toBeDefined();
		expect(Player).toBeInstanceOf(Object);
		expect(realPlayer.name).toBe("player");
	});
	test("ComputerPlayer class should exist", () => {
		expect(ComputerPlayer).toBeDefined();
		expect(Object.prototype.isPrototypeOf.call(Player, ComputerPlayer)).toBe(
			true
		);
		expect(compPlayer.name).toBe("Computer");
	});
	test("Each player should contain their own gameboard", () => {
		expect(realPlayer.gameBoard).toBeDefined();
		expect(realPlayer.gameBoard).toEqual(expect.any(GameBoard));
		expect(compPlayer.gameBoard).toBeDefined();
		expect(compPlayer.gameBoard).toEqual(expect.any(GameBoard));

		expect(realPlayer.gameBoard).not.toBe(compPlayer.gameBoard);
	});
	test("Players should include a 2d array to track attacked coordinates", () => {
		expect(realPlayer.attacks).toEqual(expect.any(Array));
		expect(compPlayer.attacks).toEqual(expect.any(Array));
		expect(realPlayer.attacks).toStrictEqual([
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
		]);
		expect(compPlayer.attacks).toStrictEqual([
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
		]);
	});
	test("Players should have a attack method", () => {
		expect(realPlayer.attack).toBeDefined();
		expect(realPlayer.attack).toBeInstanceOf(Function);
		expect(compPlayer.attack).toBeDefined();
		expect(compPlayer.attack).toBeInstanceOf(Function);
	});
	test("attack method should return an object of the coordinate that was attacked that may or may not include a hit ship", () => {
		const att1 = realPlayer.attack(compPlayer, 3, 3);
		expect(att1.ship).toEqual(expect.any(Ship));

		const att2 = realPlayer.attack(compPlayer, 0, 0);
		expect(att2.ship).toBeNull();

		const att3 = compPlayer.attack(realPlayer, 3, 0);
		expect(att3.ship).toEqual(expect.any(Ship));
	});
	test("attack method should sink an opponent's ship when the ship is hit enough number of time", () => {
		realPlayer.attack(compPlayer, 4, 3);
		const att = realPlayer.attack(compPlayer, 5, 3);

		expect(att.ship).toEqual(expect.any(Ship));
		expect(att.ship.isSunk).toBe(true);
		expect(compPlayer.gameBoard.isGameOver).toBe(true);
	});
	test("attacks array should update with the attacked coordinates", () => {
		expect(realPlayer.attacks).toStrictEqual([
			[
				"noHit",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"hit",
				"hit",
				"hit",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
		]);
		expect(compPlayer.attacks).toStrictEqual([
			[
				"unknown",
				"unknown",
				"unknown",
				"hit",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
			[
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
				"unknown",
			],
		]);
	});
	test("Player should include a method to check if a square can be attacked", () => {
		expect(realPlayer.checkValidAttackSquare).toBeDefined();
		expect(realPlayer.checkValidAttackSquare).toBeInstanceOf(Function);
		expect(realPlayer.checkValidAttackSquare(3, 3)).toBe(false);
		expect(realPlayer.checkValidAttackSquare(10, 10)).toBe(false);
	});
	test("attack should return null if the player has previously attacked the previous coordinate or the coordinate is invalid", () => {
		const att = realPlayer.attack(compPlayer, 3, 3);
		expect(att).toBeNull();

		const att2 = compPlayer.attack(realPlayer, 3, 0);
		expect(att2).toBeNull();

		const att3 = realPlayer.attack(compPlayer, 10, 10);
		expect(att3).toBeNull();
	});
	test("Player should have an attribute for missed attack", () => {
		expect(realPlayer.missedAttacks).toBeDefined();
		expect(realPlayer.missedAttacks).toBe(1);
	});
	test("Player should have a stat for ships destroyed", () => {
		expect(realPlayer.shipsDestroyed).toBeDefined();
		expect(realPlayer.shipsDestroyed).toBe(1);
	});
});
